name = "birdie"
main = "./worker.ts"              # Update path if needed
compatibility_date = "2024-02-04"
format = "modules"                # Required for ES modules

[durable_objects]
bindings = [{ name = "LLAMA_COORDINATOR", class_name = "LlamaCoordinator" }]

[[migrations]]
tag = "v1"
new_classes = ["LlamaCoordinator"]

[site]
bucket = "./dist"

[build]
command = "npm run build"
watch_dir = "app"
